#!/bin/bash -l
#SBATCH -p debug
#SBATCH -N 2
#SBATCH -C knl,quad,cache
#SBATCH --vtune
#SBATCH -t 00:10:00
#SBATCH -J rahul_job

module load vtune
module unload darshan

export OMP_NUM_THREADS=12

#srun -n 128 -c 4 amplxe-cl -collect general-exploration -r $PWD -trace-mpi -finalization-mode=none ./fftKer 8 2 10000 600 400 200 
srun -n 128 -c 4 amplxe-cl -collect memory-access -knob analyze-mem-objects=true -r $PWD -trace-mpi -finalization-mode=none ./fftKer 8 2 10000 600 400 200 
