EXE = gppKerOpenMPFor_xl.ex
SRC = gppKerOpenMPFor_xl.cpp 

#CXX = xlc++
CXX = g++

LINK = ${CXX}

#CXXFLAGS=-O3 -g -std=c++11 -qsmp -g  
#LINKFLAGS=-qsmp 

CXXFLAGS= -g -O3 -std=c++11 -fopenmp
LINKFLAGS=-fopenmp

OBJ = $(SRC:.cpp=.o)

$(EXE): $(OBJ) 
	$(CXX) $(OBJ) -o $(EXE) $(LINKFLAGS)

$(OBJ): $(SRC) 
	$(CXX) -c $(SRC) $(CXXFLAGS)

clean: 
	rm -f $(SRC).o $(EXE)
