EXE = gppKer_gpuComplexOpenMP3.0.ex
SRC = gppKer_gpuComplexOpenMP3.0.cpp 
SRC+=Complex.cpp

CXX = xlc++
#CXX = g++

LINK = ${CXX}


CXXFLAGS=-O3 -g -std=c++11 -qsmp -g  
LINKFLAGS=-qsmp 
#CXXFLAGS= -g -foffload="-lm" -foffload=nvptx-none -O3 -std=c++11 -fopenmp#nvptx-none
#LINKFLAGS=-fopenmp

OBJ = $(SRC:.cpp=.o)

$(EXE): $(OBJ) 
	$(CXX) $(OBJ) -o $(EXE) $(LINKFLAGS)

$(OBJ): $(SRC) 
	$(CXX) -c $(SRC) $(CXXFLAGS)

clean: 
	rm -f *.o gppKer_gpuComplexOpenMP3.0.ex
