EXE = gppKer_GpuComplex.ex
SRC = gppKerGpuComplex_target.cpp 

CXX = xlc++

LINK = ${CXX}

CXXFLAGS=-O3 -std=gnu++11 -g -qsmp -qoffload -Xptxas -v
LINKFLAGS=-qsmp -qoffload 

OBJ = $(SRC:.cpp=.o)

$(EXE): $(OBJ) 
	$(CXX) $(OBJ) -o $(EXE) $(LINKFLAGS)

$(OBJ): $(SRC) 
	$(CXX) -c $(SRC) $(CXXFLAGS)

clean: 
	rm -f *.o testCase_xl.ex 
