EXE = gppKer_gpuComplex.ex
SRC = gppKer_gpuComplex.cpp 
SRC+=Complex.h

#CXX = xlc++
CXX = g++

LINK = ${CXX}


#CXXFLAGS=-O3 -std=gnu++11 -g -qsmp -qoffload -Xptxas -v
#LINKFLAGS=-qsmp -qoffload 

CXXFLAGS= -g -foffload="-lm" -foffload=nvptx-none -O3 -std=c++11 -fopenmp -lineinfo 
LINKFLAGS=-fopenmp

OBJ = $(SRC:.cpp=.o)

$(EXE): $(OBJ) 
	$(CXX) $(OBJ) -o $(EXE) $(LINKFLAGS)

$(OBJ): $(SRC) 
	$(CXX) -c $(SRC) $(CXXFLAGS)

clean: 
	rm -f $(SRC).o $(EXE)
